### ISSUE TITLE
12 hour dropdown

### ISSUE THREAD

**Issue by j-walker23** [hartwig-at/fm-timepicker#2]
Hey man, great work!

Wondering if in the options this can be set to do a 12 hours clock. Like 12:00 am to 11:59 pm?

**Comment by oliversalzburg** [comment]
I assume this worked for you, otherwise, please let me know.

**Comment by j-walker23** [comment]
Wow, i don't even remember leaving this comment or what it was for. Crazy, sorry i never responded and thank you for responding!
