### ISSUE TITLE
Undefined dates cause control to error on load

### ISSUE THREAD

**Issue by svantreeck** [hartwig-at/fm-timepicker#4]
We end up binding the timepicker to a model that is fetched asynchronously, so at the time the control gets initialized, the time is undefined, and ensureTimeIsWithinBounds throws an error.  If I add `!time` to the initial check, it starts at 00:00 and the form loads without problem, which I think is OK (although it would be even better if it had no value).  The other workaround I have done is putting the time picker in a control that is excluded with ng-if when there is no value, but that's not ideal either.

			$scope.ensureTimeIsWithinBounds = function( time ) {
				// Constrain model value to be in given bounds.
				if(!time || time.isBefore( $scope.startTime ) ) {
					return moment( $scope.startTime );
				}
				if( time.isAfter( $scope.endTime ) ) {
					return moment( $scope.endTime );
				}
				return time;
			};

**Comment by oliversalzburg** [comment]
Let me see if I can come up with a better way to handle falsey models.

**Comment by oliversalzburg** [comment]
Please check 3.0.4 and see if that serves you any better :)

**Comment by svantreeck** [comment]
Thanks for the quick turnaround on that
